{{- if .Values.sharedSecretsEnabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:  
  name: dbnorthwindconnection
  namespace:  {{ .Release.Namespace }}
spec:
  encryptedData:
    connectionstring: {{ .Values.databaseConnectString }}
  template:
    data: null
    metadata:      
      name: dbnorthwindconnection
      namespace:  {{ .Release.Namespace }}
    type: Opaque
{{-end }}