# Default values for customerservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: docker.maven.incomm.com/mgkaiser/customerservice
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "Build-2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
databaseSecretName: "dbnorthwindconnection-customer"
databaseConnectString: "AgA8JDNlWaDrlbhbhRp0gFfhbDQZyrhrmk4Im2uxwRjrW+1qC08RsRLivcsGkwjxdLzJBwh5uqdDbxqg4Lf5wCGSuuPNbjQP0FRSX7n5wi6lNz1CoqB6vEkIOcn2IYkbb5gADlC89DymZPiwxeS3bdrGywrg8WtOaactFSDOU5Zht7PSaiUhn8twqNl8hN1ervzDWHQgMkDGXOx3TZC2iafBHKR8H9HVxtU+GQIgLcDmS+wUanOuMsIyDdOGKiumIjfx4Rf/qNeke8IzFODOjb/Zjl7yIFeEzbjh/HUMgF+YvN+GeUBBV+gc9E52Mh6Zxt26zMKvoYFZ4Plp+UptGDvyU4b3Q+QY8NppfhonE1Th2lbOWDd+kuqvcU6xaUmOyHYEOE9xBnltN/Vrok18YLIXAev21LOUxsdDcza8ssqazQRRd3TZm8b/bxoDWhGC+yZ0+oSrbbnhc9WrnCyhERsn9zD9znvuHF+q1B7RDqe6/0xsyWWQ0RgBP4iuaCmvxFqd0CLmDU8aYwCBN4bIcv207zkg5Ug+Ls4TP8JGjGjCO1mn8bkyn2lALJbua2hN1XtuYFOE+CCZtHOgaAO+DpooTRAz5y9batY75f1wyBGOLlnmDO2TTqnW/f1Ooy0KLAbf9ITyY1e1Eac/1RwQzMXIyZ5vwpkmBT/7OqgAlKCDySVUAQ6uw++x02nOn/iji1PR+txDS0tOVonh+uI/RRbbEei2bWHWVBXY78pyJa0g8yNyNybX49ERWTMPI/DcpdXi7z6lBi6bfV5tXIC5mopwdUNr8MN8nHdWjGAVkcBjYfdhLNnYNWnnRRC4CzwCeL+XsWKr6SwuaWAtgsoJ"
sharedSecretsEnabled: true

environment: Development
log:
  url: splunk-s1-standalone-0.splunk-s1-standalone-headless.splunk.svc.sigcntnr.incomm.com
  port: 8088
  secretname: splunk-secret
  secretkey: hec_token

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}  

podLabels:
  app: customerservice
  version: "Build-2"  

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: customerservice.sigcntnr.incomm.com
      paths:
      - path: 
        backend:
          serviceName: customerservice
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
